---
- name: this is play one
  hosts: localhost
  tasks:
    - name: this is task one
      debug:
        msg: this is message one
    - name: this is task two
      debug:
        msg: this is message two

- name: this is play two
  hosts: localhost
  tasks:
    - name: this is task three
      debug:
        msg: this is message three
