---
# playbook.yml
- hosts: peon
  vars_files:
    - vars.yml       # подгружаем внешний файл
  tasks:
    - debug:
        msg: "{{ username }}"

    - name: Создать пользователя
      user:
        name: "{{ username }}"  # alex
        groups: "sudo"
        